Fix bug calling with-all-output-to-string from eval* (issue #34)
`with-all-output-to-string` expects a `thunk`, but `eval*` calls it with
`(write-exception exn)`. This leads to a crash, for instance when it's called
from `geiser-autodoc`:

```
(geiser-autodoc '(chicken))
Error: (#f) "unbound variable": (geiser#cleanup-tasks)
Call history:

Error: call of non-procedure: #<unspecified>

	Call history:

        [...]
	geiser/chicken/src/geiser/chicken5.scm:106: chicken.port#with-error-output-to-port
```

Wrapping the calls to 'write-exception' with a lambda fixes the issue.