add geiser# prefix to geiser calls
Previously after switching to a module with say ",m my-module", evaluation of
geiser commands from a buffer failed with:

Error: unbound variable: my-module#geiser-eval

A suggestion on the #chicken channel was to prefix all geiser calls with the
module name "geiser#". I side-effect of this is that we don't need
to import geiser anymore, reducing "pollution" of the user's code with geiser
symbols.

This commit adds the geiser# prefix to geiser calls, and remove "(import geiser)" when loading chicken 5. The same could be done for chicken 4, I didn't have
time to change and test it though.